apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "local"
spec:
  configuration:
    clusters:
      - name: "deployment"
        templates:
         dataVolumeClaimTemplate: data-storage-local-template
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    volumeClaimTemplates:
      - name: data-storage-local-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
          storageClassName: local-storage
          local:
            path: /Users/zhouya/Documents/go/src/clickhouse/data
          nodeAffinity:
            required:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname=docker-desktop
                operator: In
                values:
                - kubernetes.io/os=linux