kind: Namespace
apiVersion: v1
metadata:
  name: test-clickhouse
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: pv
  namespace: test-clickhouse
spec:
  configuration:
    clusters:
      - name: "deployment"
        templates:
         dataVolumeClaimTemplate: data-storage-vc-template
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi


#  volumeClaimTemplates:
#       - name: data-storage-vc-template-1
#         spec:
#           storageClassName: gp2-resizable
#           accessModes:
#             - ReadWriteOnce
#           resources:
#             requests:
#               storage: 1Gi