apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: clickhouse-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: True
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
spec:
  storageClassName: clickhouse-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
spec:
  storageClassName: clickhouse-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/clickhouse"
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: pv
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 1
      name: clickhouse
  defaults:
    templates:
      podTemplate: pod-template
  templates:
    podTemplates:
    - name: pod-template
      spec:
        containers:
        - image: yandex/clickhouse-server:21.11
          name: clickhouse
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: clickhouse-pv
        volumes:
        - name: clickhouse-pv
          persistentVolumeClaim:
            claimName: clickhouse-pvc