apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-pv
  namespace: flow-visibility
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-pv-config
  namespace: flow-visibility
data:
  storageClassMap: |
    clickhouse-storage:
      hostDir: /data/clickhouse
      mountDir: /data/clickhouse
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-pv-node-clusterrole
  namespace: flow-visibility
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-pv-pv-binding
  namespace: flow-visibility
subjects:
- kind: ServiceAccount
  name: clickhouse-pv
  namespace: flow-visibility
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-pv-node-binding
subjects:
- kind: ServiceAccount
  name: clickhouse-pv
  namespace: flow-visibility
roleRef:
  kind: ClusterRole
  name: clickhouse-pv-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clickhouse-pv
  namespace: flow-visibility
  labels:
    app: clickhouse-pv-provisioner
spec:
  selector:
    matchLabels:
      app: clickhouse-pv-provisioner
  template:
    metadata:
      labels:
        app: clickhouse-pv-provisioner
    spec:
      serviceAccountName: clickhouse-pv
      containers:
        - name: provisioner
          image: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: clickhouse-storage
              mountPath: /data/clickhouse
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: clickhouse-pv-config
        - name: clickhouse-storage
          hostPath:
            path: /data/clickhouse
