apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  labels:
    app: clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  configuration:
    users:
      {{ .Values.clickhouse.secret.username }}/k8s_secret_password: {{ .Release.Namespace }}/clickhouse-secret/password
      {{ .Values.clickhouse.secret.username }}/networks/ip: "::/0"
    clusters:
      - name: "clickhouse"
        layout:
          {{- if .Values.clickhouse.cluster.enable }}
          shards:
            {{- range $i, $_ := until (int .Values.clickhouse.cluster.shards) }}
              - name: {{ $i | quote }}
                replicasCount: {{ $.Values.clickhouse.cluster.replicas }}
                replicas:
                  {{- range $j, $_ := until (int $.Values.clickhouse.cluster.replicas) }}
                    - name: {{ $i }}-{{ $j }}
                      templates:
                      {{- if eq $j (sub $.Values.clickhouse.cluster.replicas 1) }}
                        {{- if eq $i (sub $.Values.clickhouse.cluster.shards 1) }}
                        podTemplate: last-shard-last-replica-pod-template
                        {{- else }}
                        podTemplate: last-replica-pod-template
                        {{- end }}
                      {{- else }}
                        podTemplate: pod-template
                      {{- end }}
                  {{- end }}
            {{- end }}
          {{- else }}
          shardsCount: 1
          replicasCount: 1
          {{- end }}
    {{- if .Values.clickhouse.cluster.enable }}
    zookeeper:
      nodes:
      {{- if .Values.clickhouse.cluster.zookeeper.install }}
      - host: zookeeper.{{ .Release.Namespace }}
      {{- else }}
      {{- range $host := .Values.clickhouse.cluster.zookeeper.hosts }}
      - host: {{ $host }}
      {{- end }}
      {{- end }}
    {{- end }}
  defaults:
    templates:
      podTemplate: last-shard-last-replica-pod-template
      serviceTemplate: service-template
      {{- if .Values.clickhouse.persistentVolume.enable }}
      dataVolumeClaimTemplate: clickhouse-storage-template
      {{- end }}
  templates:
    serviceTemplates:
      - name: service-template
        spec:
          ports:
            - name: http
              port: {{ .Values.clickhouse.port.http }}
            - name: tcp
              port: {{ .Values.clickhouse.port.tcp }}
    podTemplates:
      {{- if .Values.clickhouse.cluster.enable }}
      - name: pod-template
        spec:
          containers:
            {{- include "clickhouse.container" (dict "clickhouse" .Values.clickhouse "schema" false) | indent 12 }}
          volumes:
            {{- include "clickhouse.volume" (dict "clickhouse" .Values.clickhouse) | indent 12 }}
      - name: last-replica-pod-template
        spec:
          containers:
            {{- include "clickhouse.container" (dict "clickhouse" .Values.clickhouse "schema" false) | indent 12 }}
            {{- if .Values.clickhouse.monitor.enable }}
            {{- include "clickhouse.monitor.container" (dict "clickhouse" .Values.clickhouse) | indent 12 }}
            {{- end }}
          volumes:
            {{- include "clickhouse.volume" (dict "clickhouse" .Values.clickhouse) | indent 12 }}
      {{- end }}
      - name: last-shard-last-replica-pod-template
        spec:
          containers:
            {{- include "clickhouse.container" (dict "clickhouse" .Values.clickhouse "schema" true) | indent 12 }}
            {{- if .Values.clickhouse.monitor.enable }}
            {{- include "clickhouse.monitor.container" (dict "clickhouse" .Values.clickhouse) | indent 12 }}
            {{- end }}
          volumes:
            {{- include "clickhouse.volume" (dict "clickhouse" .Values.clickhouse) | indent 12 }}
    {{- if .Values.clickhouse.persistentVolume.enable }}
    volumeClaimTemplates: 
      - name: clickhouse-storage-template
        spec:
          {{- if eq .Values.clickhouse.persistentVolume.provisioner "StorageClass" }}
          storageClassName: {{ .Values.clickhouse.persistentVolume.storageClass }}
          {{- else }}
          storageClassName: clickhouse-storage
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.storageSize }}
    {{- end }}
