apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  username: clickhouse_operator
  password: clickhouse_operator_password
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  configuration:
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: pod-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:21.11
              volumeMounts:
                - name: clickhouse-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
                - name: clickhouse-storage-volume
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: clickhouse-configmap-volume
              configMap:
                name: clickhouse-mounted-configmap
            - name: clickhouse-storage-volume
              emptyDir:
                medium: Memory
                sizeLimit: 4Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: flow-visibility
  name: clickhouse-monitor
  namespace: flow-visibility
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: flow-visibility
  name: clickhouse-monitor-role
  namespace: flow-visibility
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: flow-visibility
  name: clickhouse-monitor-role-binding
  namespace: flow-visibility
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clickhouse-monitor-role
subjects:
  - kind: ServiceAccount
    name: clickhouse-monitor
    namespace: flow-visibility
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: clickhouse-monitor
  name: clickhouse-monitor
  namespace: flow-visibility
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: clickhouse-monitor
        spec:
          serviceAccountName: clickhouse-monitor
          containers:
          - name: clickhouse-monitor
            image: aurorazhou/clickhouse-monitor:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: CH_USERNAME
                valueFrom:
                  secretKeyRef: 
                    name: clickhouse-secret
                    key: username
              - name: CH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: clickhouse-secret
                    key: password
              - name: SVC_HOST
                value: "clickhouse-clickhouse.flow-visibility.svc.cluster.local"
              - name: SVC_PORT
                value: "9000"
              - name: TABLE_NAME
                value: "default.flows"
              - name: MV_NAMES
                value: "default.flows_pod_view default.flows_node_view default.flows_policy_view"
              - name: NAMESPACE
                value: "flow-visibility"
              - name: MONITOR_LABEL
                value: "app=clickhouse-monitor"
          restartPolicy: OnFailure
