apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  username: clickhouse_operator
  password: clickhouse_operator_password
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  configuration:
    clusters:
      - name: "clickhouse"
        layout:
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplate: pod-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:21.11
              volumeMounts:
                - name: clickhouse-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
                - name: clickhouse-storage-volume
                  mountPath: /var/lib/clickhouse
          volumes:
            - name: clickhouse-configmap-volume
              configMap:
                name: clickhouse-mounted-configmap
            - name: clickhouse-storage-volume
              emptyDir:
                medium: Memory
                sizeLimit: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse-monitor
  name: clickhouse-monitor
spec:
  selector:
    matchLabels:
      app: clickhouse-monitor
  template:
    metadata:
      labels:
        app: clickhouse-monitor
    spec:
      containers:
      - name: clickhouse-monitor
        image: aurorazhou/clickhouse-monitor:deployment
        env:
          - name: CLICKHOUSE_USERNAME
            valueFrom:
              secretKeyRef: 
                name: clickhouse-secret
                key: username
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse-secret
                key: password
          - name: DB_URL
            value: "tcp://clickhouse-clickhouse.flow-visibility.svc:9000"
          - name: TABLE_NAME
            value: "default.flows"
          - name: MV_NAMES
            value: "default.flows_pod_view default.flows_node_view default.flows_policy_view"
